### ISSUE TITLE
Temperature monitoring

### ISSUE THREAD

**Issue by jbalat** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#13]
Just wanted to get this up here. 
No point being able to throw 900w at this little motor and expect it to last.
Need to monitor temperature and throttle back power to control the heat under 65 deg C using PID loop
Display some kind of warning on the screen too so the user knows what is going on

**Comment by casainho** [comment]
I am thinking to start using LM35 temperature sensor because should be easy and fast to implement the reading. BUT, it needs an ADC from STM8 that is not available on the board, the only available is throttle signal. So, for a start, I will use throttle signal (meaning I will not be able to use throttle) and later maybe I can put DS18B20 working (although should be very hard to make it working).

As for signaling to user that power is being limited due to motor temperature, maybe we can put the temperature field/temperature value flashing on that time.

**Comment by jbalat** [comment]
This sounds like a good idea. I thought you had a spare digital port free on the motor. Are you able to utilise that with a digital sensor instead.
Also I have been speaking to a friend of mine who says that you could possible measure the resistance in the motor which changes with temperature using current and voltage. If you build up a profile of the resistance vs temperature then you can use this to work out the temperature. Hope this makes sense.

**Comment by casainho** [comment]
Yes, there are 2 digital ports on an header, near the same header where throttle wire is connected. But this 2 ports has low pass filter (resistor + capacitor) and that may be a problem for the communications, also, the digital communications with DS18B20 needs a timing that I think will be hard to implement because STM8 is busy with the motor control on that range of timings.

"measure the resistance in the motor which changes with temperature using current and voltage" maybe this need the motor to be stopped, where a duty_cycle is increased up to current value get stable at a known value like 10 amps and then we known what is the voltage by multiply duty_cycle percentage * battery voltage. So R = voltage / 10 amps. Please ask to your friend if he knows a way to measure while motor is moving... because I think we can't wait for user to stop the motor and then measure the resistance. Also, our resolution of reading current is very low, like 0.25 amps step but the resistance change should be very small so I guess we do not have hardware capable to measure small resistance change and I think is needed.

**Comment by casainho** [comment]
Implemented.
