### ISSUE TITLE
Fluctuating Battery Gauge

### ISSUE THREAD

**Issue by Dirkkro** [OpenSource-EBike-firmware/TongSheng_TSDZ2_motor_controller_firmware#29]
The Batterie gauge  is  moving a lot during  use of motor assist. This is due to the electrical resistance of the  power suply system.
Cant we correct the  voltage drop due to ohnic resistance with a  correction volatage  on the Battery gauge?
U corr = U batt + (I Motor * R system) 
A rough estimate  to start with for R system 5 amps => 0.2 V 0.04 Ohm

**Comment by casainho** [comment]
And the user could setup the battery internal resistance value on the LCD3.

Since on LCD3 we can limit the max current value and read the battery voltage, I think is easy for user to find the resistance value, by riding the motor let's say at 10 amps limit and see the voltage drop, that way it should be easy to calculate the resistance.

**Comment by casainho** [comment]
Implemented.
